plugins {
    id 'com.android.application'
}

android {
    namespace 'com.hk'
    compileSdk 34

    defaultConfig {
        applicationId "com.hk"
        minSdk 24
        targetSdk 34
        versionCode 1
        versionName "1.0"
    }
}

// ==========================================
// HK-OPERATION: ARSENAL & DEPENDENCIES INJECTED
// ==========================================
dependencies {
    // Swipe-to-Refresh Engine loaded
    implementation 'androidx.swiperefreshlayout:swiperefreshlayout:1.1.0'
}
