name: HK-Auto-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle (Force Stable Engine)
        uses: gradle/actions/setup-gradle@v3
        with:
          gradle-version: '8.4' # HK-OPERATION: Forced Downgrade to bypass 9.4.0 crash
          
      - name: Build Elite APK
        working-directory: ./HK-Browser
        run: gradle assembleDebug # Direct global hit, no gradlew needed
        
      - name: Upload HK Payload
        uses: actions/upload-artifact@v4
        with:
          name: HK-Browser-APK
          path: HK-Browser/**/*.apk
