name: HK-Auto-Build
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        
      - name: Build Elite APK
        working-directory: ./HK-Browser  # <-- Ye line engine ko sahi rasta dikhayegi
        run: gradle assembleDebug
        
      - name: Upload HK Payload
        uses: actions/upload-artifact@v4
        with:
          name: HK-Browser-APK
          path: HK-Browser/app/build/outputs/apk/debug/app-debug.apk # <-- Path updated
